global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'llmstack'
    static_configs:
      - targets: ['host.docker.internal:3000']
  
  - job_name: 'ollama'
    static_configs:
      - targets: ['host.docker.internal:11434']